fallback = ''
separator = ' '

[matching]
'foot' = ''
'firewall-config' = ''
'com.github.gittyup.gittyup' = ''
'ranger' = ''
'org.fedoraproject.MediaWriter' = ''
'org.gnome.Boxes' = ''
'io.github.mhogomchungu.sirikali' = ''
'thunar' = ''
'FreeFileSync' = ''
'org.kde.dolphin' = ''
'brave-browser' = ''
'org.qutebrowser.qutebrowser' = ''
'Com.ulaa.Ulaa' = ''
'Mail' = ''
'LibreWolf' = ''
'Mullvad Browser' = ''
'Microsoft-edge' = ''
'filezilla' = ''
'Opera' = ''
'org.mozilla.firefox' = ''
'org.mozilla.Thunderbird' = ''
'com.vscodium.codium-url-handler' = ''
'Code - OSS' = ''
'Code' = ''
'libreoffice-writer' = ''
'obsidian' = ''
'ONLYOFFICE' = ''
'Notesnook' = ''
'Standard Notes' = ''
'Zettlr' = ''
'com.belmoussaoui.Obfuscate' = ''
'calibre-gui' = ''
'calibre-ebook-edit' = ''
'calibre-ebook-viewer' = ''
'org.kde.okular' = ''
'vlc' = ''
'Audacity' = ''
'org.kde.kdenlive' = ''
'kapsa' = ''
'Gimp-2.10' = ''
'com.dec05eba.gpu_screen_recorder' = ''
'Peek' = ''
'org.inkscape.Inkscape' = ''
'LosslessCut' = ''
'org.telegram.desktop' = ''
'zoom' = ''
'discord' = ''
'org-jdownloader-update-launcher-JDLauncher' = ''
'/nvim ?\w*/' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
'Alacritty' = ''